include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_fields
    - avoid_print
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - "**/*.g.dart"
    - "build/**"
