import 'package:flutter/material.dart';

import '../theme.dart';

/// Step 3: the reel is being generated by the Cinemory API.
class GeneratingScreen extends StatelessWidget {
  const GeneratingScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CircularProgressIndicator(color: CinemoryTheme.gold),
            SizedBox(height: 24),
            Text('Composing your reel…'),
            SizedBox(height: 8),
            Text(
              'Scoring scenes, planning cuts, sealing provenance.',
              style: TextStyle(color: Colors.white54, fontSize: 12),
            ),
          ],
        ),
      ),
    );
  }
}
